# @generated by datamodel-codegen:
#   filename:  extent/midi_ticks.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct


class MidiTicks(Struct, tag_field="extent_type", tag="midi_ticks"):
    tick: Annotated[list[float], Meta(description="An array of MIDI tick values.")]
