# @generated by datamodel-codegen:
#   filename:  extent/quarters_time_float.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct


class QuartersTimeFloat(Struct, tag_field="extent_type", tag="quarters_time.float"):
    quarter: Annotated[
        list[float], Meta(description="Array of time points in quarter notes.")
    ]
