# @generated by datamodel-codegen:
#   filename:  extent/quarters_interval_fraction.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct

from .. import core


class QuartersIntervalFraction(
    Struct, tag_field="extent_type", tag="quarters_interval.fraction"
):
    quarter: Annotated[
        list[core.Fraction],
        Meta(description="Array of interval start times in fractional quarter notes."),
    ]
    duration: Annotated[
        list[core.FractionNonnegative],
        Meta(description="Array of interval durations in fractional quarter notes."),
    ]
