# @generated by datamodel-codegen:
#   filename:  extent/quarter_interval.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct
from pyarrow import Array


class QuarterIntervalExtent(Struct, tag_field="extent_type", tag="quarter_interval"):
    """
    Interval extents measured in quarter notes (crotchet beats) rather than seconds. The unit is carried by the extent_type tag and these descriptions: BOPP extent structs have no separate unit field, so a dedicated tagged type is the idiomatic way to indicate non-second coordinates.
    """

    start: Annotated[
        Annotated[Array, "float32"],
        Meta(
            description="Array of start positions in quarter notes, converted from quarterbeats_all_endings fractions."
        ),
    ]
    duration: Annotated[
        Annotated[Array, "float32"],
        Meta(
            description="Array of interval durations in quarter notes (from duration_qb)."
        ),
    ]
