# @generated by datamodel-codegen:
#   filename:  extent/quarters_time_fraction.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct

from .. import core


class QuartersTimeFraction(
    Struct, tag_field="extent_type", tag="quarters_time.fraction"
):
    quarter: Annotated[
        list[core.Fraction],
        Meta(description="Array of time points in fractional quarter notes."),
    ]
