# @generated by datamodel-codegen:
#   filename:  extent/quarters_interval_float.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct

type DurationItem = Annotated[float, Meta(ge=0.0)]


class QuartersIntervalFloat(
    Struct, tag_field="extent_type", tag="quarters_interval.float"
):
    quarter: Annotated[
        list[float], Meta(description="Array of interval start times in quarter notes.")
    ]
    duration: Annotated[
        list[DurationItem],
        Meta(description="Array of interval durations in quarter notes."),
    ]
