# @generated by datamodel-codegen:
#   filename:  extent/time_interval.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct

from .. import coordinate


class TimeIntervalExtent(Struct, tag_field="extent_type", tag="time_interval"):
    """
    Left-inclusive, right-exclusive intervals [start, start + duration), expressed as two coordinates that must share the same unit.
    """

    start: Annotated[
        coordinate.Coordinate, Meta(description="N interval start positions.")
    ]
    duration: Annotated[
        coordinate.Coordinate,
        Meta(description="N interval durations (elapsed extents), same unit as start."),
    ]
