# @generated by datamodel-codegen:
#   filename:  extent/times.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct

from .. import coordinate


class Timestamps(Struct, tag_field="extent_type", tag="timestamps"):
    """
    Instants: one coordinate per observation.
    """

    time: Annotated[
        coordinate.Coordinate, Meta(description="N positions on the timeline.")
    ]
