# @generated by datamodel-codegen:
#   filename:  extent/time_frequency_box.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct
from pyarrow import Array

from .. import coordinate


class TimeFrequencyBoxExtent(Struct, tag_field="extent_type", tag="TimeFrequencyBox"):
    start: Annotated[coordinate.Coordinate, Meta(description="N box start positions.")]
    duration: Annotated[
        coordinate.Coordinate, Meta(description="N box durations, same unit as start.")
    ]
    freq_min: Annotated[
        Annotated[Array, "float32"],
        Meta(description="Array of minimum frequencies in Hz."),
    ]
    freq_max: Annotated[
        Annotated[Array, "float32"],
        Meta(description="Array of maximum frequencies in Hz."),
    ]
