name: bopp-lint
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - codespell
  - mypy
  - ruff
  - numpydoc>=1.8.0
  - sphinx>=5.1.0
  - pandas-stubs
  - polars
  - pyarrow-stubs
  - msgspec
  - mir_eval>=0.7
  - numpy>=1.20.0
  - scipy>=1.7.0
  - pytest
