# @generated by datamodel-codegen:
#   filename:  payload/dcml_harmony.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct
from pyarrow import Array


class DcmlHarmonyPayload(Struct, tag_field="payload_type", tag="dcml_harmony"):
    """
    Columnar DCML harmony annotation labels from the 'expanded' facet of the Distant Listening Corpus (all descriptor columns from 'label' onwards, each as a parallel array).
    """

    label: Annotated[
        Array, Meta(description="String corresponding to the entire annotation label.")
    ]
    globalkey: Annotated[
        Array,
        Meta(
            description="The key of the entire piece as note name, lowercase designating a minor key."
        ),
    ]
    localkey: Annotated[
        Array,
        Meta(
            description="The key that a Roman numeral is relative to, expressed as a Roman numeral relative to the global key."
        ),
    ]
    pedal: Annotated[
        Array, Meta(description="Pedal point, specified as Roman numeral.")
    ]
    chord: Annotated[
        Array,
        Meta(
            description="The part of an annotation label that corresponds to the actual chord label."
        ),
    ]
    special: Annotated[
        Array,
        Meta(
            description='Special labels such as "Fr6" or "Ger65" which are converted internally to Roman numerals.'
        ),
    ]
    numeral: Annotated[
        Array,
        Meta(
            description="The Roman numeral part of a DCML label, lowercase for all chords with a minor third."
        ),
    ]
    form: Annotated[Array, Meta(description="Chord category: %, o, +, M, +M.")]
    figbass: Annotated[
        Array,
        Meta(
            description="Chord inversion: 7, 65, 43, 2, 64, 6 or empty for root position."
        ),
    ]
    changes: Annotated[
        Array,
        Meta(
            description="Alterations, suspensions, additions, and omissions, written within parentheses in the chord label."
        ),
    ]
    relativeroot: Annotated[
        Array,
        Meta(
            description="The Roman numeral following the / in applied chords. Can itself include a /. For example, V/V if the label pertains to the major scale on the second scale degree."
        ),
    ]
    cadence: Annotated[
        Array,
        Meta(
            description="Cadence: PAC, IAC, EC, DC, PC, HC, and HC subtypes such as HC.SIM."
        ),
    ]
    phraseend: Annotated[
        Array,
        Meta(
            description="The phrase annotation part of a DCML label, can be {, }, or }{."
        ),
    ]
    chord_type: Annotated[
        Array,
        Meta(
            description="Chord type: 'M', 'm', 'o', '+', 'mm7', 'Mm7', 'MM7', 'mM7', 'o7', '%7', '+7', '+M7'."
        ),
    ]
    globalkey_is_minor: Annotated[
        Array,
        Meta(
            description="Boolean that is 1 if the piece is in minor and 0 if it is in major."
        ),
    ]
    localkey_is_minor: Annotated[
        Array,
        Meta(
            description="Boolean that is 1 if the local key is minor and 0 if it is major."
        ),
    ]
    chord_tones: Annotated[
        Array,
        Meta(
            description="Tones expressed by the label, as fifth intervals relative to the local tonic. The datapackage descriptor declares strings, but dimcat materializes tuples of integers; BOPP stores them as variable-length integer arrays."
        ),
    ]
    added_tones: Annotated[
        Array,
        Meta(
            description="Chord tones considered as added, expressed as fifth intervals relative to the local tonic. The datapackage descriptor declares strings, but dimcat materializes tuples of integers; BOPP stores them as variable-length integer arrays."
        ),
    ]
    root: Annotated[Array, Meta(description="Root, pertaining to MuseScore encoding.")]
    bass_note: Annotated[
        Array,
        Meta(
            description="Lowest note designated by the chord label, expressed as fifth intervals relative to the local tonic."
        ),
    ]
    alt_label: Annotated[
        Array,
        Meta(
            description="Another interpretation of the same chord which the annotator finds equally or slightly less convincing."
        ),
    ]
    volta: Annotated[
        Array, Meta(description="Number of an ending bracket, given as integer.")
    ]
    placement: Annotated[
        Array,
        Meta(
            description="Placement of the annotation label in the score (e.g. above/below)."
        ),
    ]
