# @generated by datamodel-codegen:
#   filename:  payload/score_note.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct
from pyarrow import Array


class ScoreNotePayload(Struct, tag_field="payload_type", tag="score_note"):
    """
    Columnar note events from the 'notes' facet of the Distant Listening Corpus (all descriptor columns except the row identifiers and the two extent columns, each as a parallel array).
    """

    mc: Annotated[
        Array,
        Meta(
            description="Running count of encoded <Measure> tags which do not necessarily express a full measure (e.g. in case of an anacrusis)."
        ),
    ]
    mn: Annotated[
        Array,
        Meta(
            description="Measure number as printed in the score, computed from mc, dont_count and numbering_offset."
        ),
    ]
    quarterbeats: Annotated[
        Array,
        Meta(
            description="Distance from the piece's beginning, leaving out alternative endings. The descriptor declares fraction strings; dimcat materializes Fractions, which BOPP stores as floats (quarter notes)."
        ),
    ]
    mc_onset: Annotated[
        Array,
        Meta(
            description="Distance of an event from the beginning of the <Measure> tag. The descriptor declares fraction strings; dimcat materializes Fractions, which BOPP stores as floats (quarter notes)."
        ),
    ]
    mn_onset: Annotated[
        Array,
        Meta(
            description="Distance from the beginning of the logical measure. The descriptor declares fraction strings; dimcat materializes Fractions, which BOPP stores as floats (quarter notes)."
        ),
    ]
    timesig: Annotated[
        Array, Meta(description='Time signature, given as string, e.g. "4/4".')
    ]
    staff: Annotated[
        Array,
        Meta(
            description="Number of the staff where an event occurs, 1 designating the top staff."
        ),
    ]
    voice: Annotated[
        Array,
        Meta(
            description="Notational layer, a number between 1-4 where 1 is MuseScore's default layer."
        ),
    ]
    duration: Annotated[
        Array,
        Meta(
            description="Duration as fraction of a whole note. The descriptor declares fraction strings; dimcat materializes Fractions, which BOPP stores as floats (whole notes)."
        ),
    ]
    gracenote: Annotated[
        Array,
        Meta(
            description='Name given to a type of grace note in the MuseScore encoding, e.g. "grace16".'
        ),
    ]
    nominal_duration: Annotated[
        Array,
        Meta(
            description="The duration corresponding to a note/rest value without applying any dots or n-tuplets, as fraction of a whole note. The descriptor declares fraction strings; dimcat materializes Fractions, which BOPP stores as floats (whole notes)."
        ),
    ]
    scalar: Annotated[
        Array,
        Meta(
            description="Decimal value reflecting all dots and n-tuplets modifying the duration of a note/rest. The descriptor declares fraction strings; dimcat materializes Fractions, which BOPP stores as floats."
        ),
    ]
    tied: Annotated[
        Array,
        Meta(
            description="1 if a note is tied to the following one, -1 if it is being tied to by the previous one, 0 if both."
        ),
    ]
    tpc: Annotated[
        Array,
        Meta(
            description="Tonal pitch class, specified on the line of fifths such that 0 = C, 1 = G, -1 = F, etc."
        ),
    ]
    midi: Annotated[
        Array,
        Meta(
            description="MIDI pitch, value between 0 and 127 where 60 = C4, 61 = C#4/Db4, etc."
        ),
    ]
    name: Annotated[Array, Meta(description='Note name with octave, e.g. "C4".')]
    octave: Annotated[
        Array,
        Meta(
            description="Octave number where 4 is the middle octave (' in Helmholtz notation)."
        ),
    ]
    chord_id: Annotated[Array, Meta(description="Row in the chords table.")]
    tremolo: Annotated[
        Array, Meta(description="Tremolo marking from the MuseScore encoding.")
    ]
    volta: Annotated[
        Array, Meta(description="Number of an ending bracket, given as integer.")
    ]
    tuning: Annotated[
        Array, Meta(description="Detuning information from the MuseScore encoding.")
    ]
