# @generated by datamodel-codegen:
#   filename:  payload/score_figured_bass.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct
from pyarrow import Array

from .. import core


class ScoreFiguredBassPayload(
    Struct, tag_field="payload_type", tag="score_figured_bass"
):
    """
    Thoroughbass figures. One of the event types of the Distant Listening Corpus 'chords' facet (event == 'FiguredBass'). All columns are parallel arrays; missing values are null.
    """

    mc: Annotated[
        Array,
        Meta(
            description="Running count of encoded <Measure> tags which do not necessarily express a full measure (e.g. in case of an anacrusis)."
        ),
    ]
    mn: Annotated[
        Array,
        Meta(
            description="Measure number as printed in the score, computed from mc, dont_count and numbering_offset."
        ),
    ]
    quarterbeats: Annotated[
        core.FractionBuffer,
        Meta(
            description="Distance from the piece's beginning. By default, only second endings are taken into account to reflect the proportions of a simply playthrough without repeats. Exact fraction."
        ),
    ]
    mc_onset: Annotated[
        core.FractionBuffer,
        Meta(
            description="Distance of an event from the beginning of the <Measure> tag. Exact fraction."
        ),
    ]
    mn_onset: Annotated[
        core.FractionBuffer,
        Meta(
            description="Distance from the beginning of the logical measure. Relevant, for example, to compute the metric position of an event. Exact fraction."
        ),
    ]
    timesig: Annotated[Array, Meta(description='Given as string, e.g. "4/4".')]
    staff: Annotated[
        Array,
        Meta(
            description="Number of the staff where an event occurs, 1 designating the top staff."
        ),
    ]
    voice: Annotated[
        Array,
        Meta(
            description="A number between 1-4 where 1 is MuseScore's default layer (blue), 2 the second layer in green with downward stems, etc."
        ),
    ]
    duration: Annotated[
        core.FractionBuffer,
        Meta(description="As fraction of a whole note. Exact fraction."),
    ]
    volta: Annotated[
        Array, Meta(description="Number of an ending bracket, given as integer.")
    ]
    slur: Annotated[
        Array,
        Meta(
            description="IDs of active slurs that a chord falls under, as a tuple of integers."
        ),
    ]
    thoroughbass_duration: Annotated[
        Array, Meta(description="Duration of the figure as fraction of a whole note.")
    ]
    thoroughbass_level_1: Annotated[Array, Meta(description="Topmost figure.")]
    thoroughbass_level_2: Annotated[Array, Meta(description="Second figure.")]
    thoroughbass_level_3: Annotated[Array, Meta(description="Third figure.")]
    thoroughbass_level_4: Annotated[Array, Meta(description="Fourth figure.")]
