# @generated by datamodel-codegen:
#   filename:  payload/score_note.json

from __future__ import annotations

from typing import Annotated

from msgspec import UNSET, Meta, Struct, UnsetType

from .. import core

type MidiItem = Annotated[int, Meta(ge=0, le=127)]


type StaffItem = Annotated[int, Meta(ge=1)]


type VoiceItem = Annotated[int, Meta(ge=1)]


type McItem = Annotated[int, Meta(ge=1)]


type TiedItem = Annotated[int, Meta(ge=-1, le=1)] | None


type ChordIdItem = Annotated[int, Meta(ge=0)]


type VoltaItem = Annotated[int, Meta(ge=1)] | None


class ScoreNotePayload(Struct, tag_field="payload_type", tag="score_note"):
    """
    Score notes, one row per note. Shared by all symbolic datasets; only midi and tpc are required.
    """

    midi: Annotated[list[MidiItem], Meta(description="MIDI note numbers (0-127).")]
    tpc: Annotated[
        list[int],
        Meta(
            description="Tonal pitch classes as positions on the line of fifths with C = 0 (G = 1, F = -1, C# = 7, Bb = -2)."
        ),
    ]
    name: (
        Annotated[
            list[str],
            Meta(
                description="Note names with octave in scientific pitch notation, e.g. 'C#4'."
            ),
        ]
        | UnsetType
    ) = UNSET
    octave: (
        Annotated[
            list[int],
            Meta(
                description="Octave numbers in scientific pitch notation (C4 is middle C)."
            ),
        ]
        | UnsetType
    ) = UNSET
    staff: (
        Annotated[list[StaffItem], Meta(description="Staff numbers, 1 = top staff.")]
        | UnsetType
    ) = UNSET
    voice: (
        Annotated[
            list[VoiceItem],
            Meta(description="Voice (layer) numbers within the staff, 1-based."),
        ]
        | UnsetType
    ) = UNSET
    mc: (
        Annotated[
            list[McItem],
            Meta(
                description="Measure counts: 1-based index of the measure unit in the encoded score (ms3 'mc')."
            ),
        ]
        | UnsetType
    ) = UNSET
    mn: (
        Annotated[
            list[int],
            Meta(
                description="Measure numbers as printed in the score (ms3 'mn'; 0 for an anacrusis)."
            ),
        ]
        | UnsetType
    ) = UNSET
    measure: (
        Annotated[
            list[int],
            Meta(
                description="Measure numbers in the source dataset's own convention, for datasets that distinguish neither mc nor mn (e.g. BPS-FH)."
            ),
        ]
        | UnsetType
    ) = UNSET
    tied: (
        Annotated[
            list[TiedItem],
            Meta(
                description="Tie status: 1 = a tie starts here, 0 = tied from and to another note, -1 = a tie ends here; null = not tied."
            ),
        ]
        | UnsetType
    ) = UNSET
    gracenote: (
        Annotated[
            list[str | None],
            Meta(
                description="Grace note type (e.g. 'acciaccatura', 'appoggiatura', 'grace16'); null for regular notes."
            ),
        ]
        | UnsetType
    ) = UNSET
    nominal_duration: (
        Annotated[
            list[core.FractionNonnegative],
            Meta(
                description="Notated durations as fractions of a whole note before dots and tuplets are applied (e.g. [1, 4] for a quarter note)."
            ),
        ]
        | UnsetType
    ) = UNSET
    scalar: (
        Annotated[
            list[core.FractionNonnegative],
            Meta(
                description="Factors that dots and tuplets apply to nominal_duration (e.g. [3, 2] for a dotted note, [2, 3] inside a triplet)."
            ),
        ]
        | UnsetType
    ) = UNSET
    chord_id: (
        Annotated[
            list[ChordIdItem],
            Meta(
                description="Identifier of the chord (stem) the note belongs to, unique within the piece."
            ),
        ]
        | UnsetType
    ) = UNSET
    tremolo: (
        Annotated[
            list[str | None],
            Meta(
                description="Tremolo specification as encoded by the source (e.g. '1/2_r16_0'); null when absent."
            ),
        ]
        | UnsetType
    ) = UNSET
    volta: (
        Annotated[
            list[VoltaItem],
            Meta(
                description="Volta (ending) number of the measure the note belongs to; null outside voltas."
            ),
        ]
        | UnsetType
    ) = UNSET
    tuning: (
        Annotated[
            list[float | None],
            Meta(description="Tuning offset in cents; null when not specified."),
        ]
        | UnsetType
    ) = UNSET
    anchor: (
        Annotated[
            list[str],
            Meta(
                description="Identifier of the note in its source document, e.g. a match-file anchor such as 'n238'."
            ),
        ]
        | UnsetType
    ) = UNSET
