# @generated by datamodel-codegen:
#   filename:  payload/score_chord.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct
from pyarrow import Array

from .. import core


class ScoreChordPayload(Struct, tag_field="payload_type", tag="score_chord"):
    """
    Sounding chords/rests from the MuseScore <Chord> layer; every note in the notes facet points here via chord_id. One of the event types of the Distant Listening Corpus 'chords' facet (event == 'Chord'). All columns are parallel arrays; missing values are null.
    """

    mc: Annotated[
        Array,
        Meta(
            description="Running count of encoded <Measure> tags which do not necessarily express a full measure (e.g. in case of an anacrusis)."
        ),
    ]
    mn: Annotated[
        Array,
        Meta(
            description="Measure number as printed in the score, computed from mc, dont_count and numbering_offset."
        ),
    ]
    quarterbeats: Annotated[
        core.FractionBuffer,
        Meta(
            description="Distance from the piece's beginning. By default, only second endings are taken into account to reflect the proportions of a simply playthrough without repeats. Exact fraction."
        ),
    ]
    mc_onset: Annotated[
        core.FractionBuffer,
        Meta(
            description="Distance of an event from the beginning of the <Measure> tag. Exact fraction."
        ),
    ]
    mn_onset: Annotated[
        core.FractionBuffer,
        Meta(
            description="Distance from the beginning of the logical measure. Relevant, for example, to compute the metric position of an event. Exact fraction."
        ),
    ]
    timesig: Annotated[Array, Meta(description='Given as string, e.g. "4/4".')]
    staff: Annotated[
        Array,
        Meta(
            description="Number of the staff where an event occurs, 1 designating the top staff."
        ),
    ]
    voice: Annotated[
        Array,
        Meta(
            description="A number between 1-4 where 1 is MuseScore's default layer (blue), 2 the second layer in green with downward stems, etc."
        ),
    ]
    duration: Annotated[
        core.FractionBuffer,
        Meta(description="As fraction of a whole note. Exact fraction."),
    ]
    volta: Annotated[
        Array, Meta(description="Number of an ending bracket, given as integer.")
    ]
    slur: Annotated[
        Array,
        Meta(
            description="IDs of active slurs that a chord falls under, as a tuple of integers."
        ),
    ]
    gracenote: Annotated[
        Array,
        Meta(
            description='Name given to a type of grace note in the MuseScore encoding, e.g. "grace16"'
        ),
    ]
    nominal_duration: Annotated[
        core.FractionBuffer,
        Meta(
            description='The duration corresponding to a note/rest value without applying any dots or n-tuplets, as fraction of a whole note. Multiplied with "scalar" to yield the actual duration of the note/rest. Exact fraction.'
        ),
    ]
    scalar: Annotated[
        Array,
        Meta(
            description='Decimal value reflecting all dots and n-tuplets modifying the duration of a note/rest. Yields the actual duration when multiplied with "nominal_duration".'
        ),
    ]
    chord_id: Annotated[Array, Meta(description="Row in the chords table.")]
    articulation: Annotated[
        Array, Meta(description="Articulation sign(s) attached to the chord.")
    ]
    crescendo_hairpin: Annotated[
        Array, Meta(description="IDs of active crescendo hairpins, comma-separated.")
    ]
    decrescendo_hairpin: Annotated[
        Array, Meta(description="IDs of active decrescendo hairpins, comma-separated.")
    ]
    diminuendo_line: Annotated[
        Array, Meta(description="IDs of active diminuendo text lines, comma-separated.")
    ]
    crescendo_line: Annotated[
        Array, Meta(description="IDs of active crescendo text lines, comma-separated.")
    ]
    tremolo: Annotated[Array, Meta(description="Tremolo type, e.g. 'r16'.")]
    lyrics_1: Annotated[Array, Meta(description="First lyrics verse syllable.")]
    lyrics_2: Annotated[Array, Meta(description="Second lyrics verse syllable.")]
    lyrics_3: Annotated[Array, Meta(description="Third lyrics verse syllable.")]
