# @generated by datamodel-codegen:
#   filename:  payload/score_tempo.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct
from pyarrow import Array

from .. import core


class ScoreTempoPayload(Struct, tag_field="payload_type", tag="score_tempo"):
    """
    Tempo markings with their quarter-per-minute interpretation. One of the event types of the Distant Listening Corpus 'chords' facet (event == 'Tempo'). All columns are parallel arrays; missing values are null.
    """

    mc: Annotated[
        Array,
        Meta(
            description="Running count of encoded <Measure> tags which do not necessarily express a full measure (e.g. in case of an anacrusis)."
        ),
    ]
    mn: Annotated[
        Array,
        Meta(
            description="Measure number as printed in the score, computed from mc, dont_count and numbering_offset."
        ),
    ]
    quarterbeats: Annotated[
        core.FractionBuffer,
        Meta(
            description="Distance from the piece's beginning. By default, only second endings are taken into account to reflect the proportions of a simply playthrough without repeats. Exact fraction."
        ),
    ]
    mc_onset: Annotated[
        core.FractionBuffer,
        Meta(
            description="Distance of an event from the beginning of the <Measure> tag. Exact fraction."
        ),
    ]
    mn_onset: Annotated[
        core.FractionBuffer,
        Meta(
            description="Distance from the beginning of the logical measure. Relevant, for example, to compute the metric position of an event. Exact fraction."
        ),
    ]
    timesig: Annotated[Array, Meta(description='Given as string, e.g. "4/4".')]
    staff: Annotated[
        Array,
        Meta(
            description="Number of the staff where an event occurs, 1 designating the top staff."
        ),
    ]
    voice: Annotated[
        Array,
        Meta(
            description="A number between 1-4 where 1 is MuseScore's default layer (blue), 2 the second layer in green with downward stems, etc."
        ),
    ]
    duration: Annotated[
        core.FractionBuffer,
        Meta(description="As fraction of a whole note. Exact fraction."),
    ]
    volta: Annotated[
        Array, Meta(description="Number of an ending bracket, given as integer.")
    ]
    slur: Annotated[
        Array,
        Meta(
            description="IDs of active slurs that a chord falls under, as a tuple of integers."
        ),
    ]
    tempo: Annotated[
        Array,
        Meta(
            description="Tempo text as printed, e.g. 'Allegro' or a metronome marking."
        ),
    ]
    qpm: Annotated[Array, Meta(description="Tempo in quarter notes per minute.")]
    tempo_visible: Annotated[
        Array, Meta(description="Whether the tempo marking is printed.")
    ]
    metronome_base: Annotated[
        Array, Meta(description="Note value of the metronome marking (SMuFL glyph).")
    ]
    metronome_number: Annotated[
        Array, Meta(description="Beats per minute of the metronome marking.")
    ]
