# @generated by datamodel-codegen:
#   filename:  coordinate.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct
from pyarrow import Array

from . import core


class NumberCoordinate(Struct, tag_field="unit", tag="number"):
    """
    Generic dimensionless number (logical domain escape hatch). Number type: float.
    """

    values: Annotated[
        Annotated[Array, "float64"],
        Meta(description="Coordinate values in number, stored as float."),
    ]


class FloatingMeasuresCoordinate(Struct, tag_field="unit", tag="floating_measures"):
    """
    Measures, with fractional part denoting position within the measure (logical domain). Number type: float.
    """

    values: Annotated[
        Annotated[Array, "float64"],
        Meta(description="Coordinate values in floating_measures, stored as float."),
    ]


class TicksCoordinate(Struct, tag_field="unit", tag="ticks"):
    """
    Ticks, MIDI's time unit (logical domain, discrete). Number type: int.
    """

    values: Annotated[
        Annotated[Array, "int64"],
        Meta(description="Coordinate values in ticks, stored as int."),
    ]


class MillisecondsCoordinate(Struct, tag_field="unit", tag="milliseconds"):
    """
    Milliseconds (physical domain). Number type: float.
    """

    values: Annotated[
        Annotated[Array, "float64"],
        Meta(description="Coordinate values in milliseconds, stored as float."),
    ]


class SecondsCoordinate(Struct, tag_field="unit", tag="seconds"):
    """
    Seconds (physical domain). Number type: float.
    """

    values: Annotated[
        Annotated[Array, "float64"],
        Meta(description="Coordinate values in seconds, stored as float."),
    ]


class MinutesCoordinate(Struct, tag_field="unit", tag="minutes"):
    """
    Minutes (physical domain). Number type: float.
    """

    values: Annotated[
        Annotated[Array, "float64"],
        Meta(description="Coordinate values in minutes, stored as float."),
    ]


class SamplesCoordinate(Struct, tag_field="unit", tag="samples"):
    """
    Audio samples (physical domain, discrete). Number type: int.
    """

    values: Annotated[
        Annotated[Array, "int64"],
        Meta(description="Coordinate values in samples, stored as int."),
    ]


class FramesCoordinate(Struct, tag_field="unit", tag="frames"):
    """
    Frames, e.g. video or analysis frames (physical domain, discrete). Number type: int.
    """

    values: Annotated[
        Annotated[Array, "int64"],
        Meta(description="Coordinate values in frames, stored as int."),
    ]


class PixelsCoordinate(Struct, tag_field="unit", tag="pixels"):
    """
    Pixels (graphical domain, discrete). Number type: int.
    """

    values: Annotated[
        Annotated[Array, "int64"],
        Meta(description="Coordinate values in pixels, stored as int."),
    ]


class MetersCoordinate(Struct, tag_field="unit", tag="meters"):
    """
    Meters (graphical domain). Number type: float.
    """

    values: Annotated[
        Annotated[Array, "float64"],
        Meta(description="Coordinate values in meters, stored as float."),
    ]


class CentimetersCoordinate(Struct, tag_field="unit", tag="centimeters"):
    """
    Centimeters (graphical domain). Number type: float.
    """

    values: Annotated[
        Annotated[Array, "float64"],
        Meta(description="Coordinate values in centimeters, stored as float."),
    ]


class MillimetersCoordinate(Struct, tag_field="unit", tag="millimeters"):
    """
    Millimeters (graphical domain). Number type: float.
    """

    values: Annotated[
        Annotated[Array, "float64"],
        Meta(description="Coordinate values in millimeters, stored as float."),
    ]


class InchesCoordinate(Struct, tag_field="unit", tag="inches"):
    """
    Inches (graphical domain). Number type: float.
    """

    values: Annotated[
        Annotated[Array, "float64"],
        Meta(description="Coordinate values in inches, stored as float."),
    ]


class PointsCoordinate(Struct, tag_field="unit", tag="points"):
    """
    Typographic points (graphical domain). Number type: float.
    """

    values: Annotated[
        Annotated[Array, "float64"],
        Meta(description="Coordinate values in points, stored as float."),
    ]


class WholeNoteCoordinate(Struct, tag_field="unit", tag="whole_note"):
    """
    Whole notes (logical domain). Number type: fraction.
    """

    values: Annotated[
        core.FractionBuffer,
        Meta(description="Coordinate values in whole_note, stored as fraction."),
    ]


class QuartersCoordinate(Struct, tag_field="unit", tag="quarters"):
    """
    Quarter notes / crotchet beats (logical domain). Number type: fraction.
    """

    values: Annotated[
        core.FractionBuffer,
        Meta(description="Coordinate values in quarters, stored as fraction."),
    ]


type Coordinate = Annotated[
    NumberCoordinate
    | FloatingMeasuresCoordinate
    | WholeNoteCoordinate
    | QuartersCoordinate
    | TicksCoordinate
    | MillisecondsCoordinate
    | SecondsCoordinate
    | MinutesCoordinate
    | SamplesCoordinate
    | FramesCoordinate
    | PixelsCoordinate
    | MetersCoordinate
    | CentimetersCoordinate
    | MillimetersCoordinate
    | InchesCoordinate
    | PointsCoordinate,
    Meta(
        description="A columnar array of positions (or elapsed extents) on a timeline, following the timetoalign model: a coordinate is a value measured in a unit, and every unit is coupled to exactly one number type. Discrete units (ticks, samples, frames, pixels) are int; continuous symbolic units (quarters, whole_note) are exact fractions; all other continuous units are float. The `unit` tag therefore fully determines the buffer type, so consumers never guess precision from the data.",
        title="Coordinate",
    ),
]
