# @generated by datamodel-codegen:
#   filename:  event_block.json

from __future__ import annotations

from typing import Annotated

from msgspec import UNSET, Meta, UnsetType

from bopp.base import BoppBase

from . import confidences, extents, payloads


class EventBlock(BoppBase):
    """
    One homogeneous block of events inside a ScoreObject: parallel extent/payload/confidence arrays for a single payload type. Structurally an Annotation without the file-level header.
    """

    extent: Annotated[
        extents.AnyExtent, Meta(description="The parallel array of time boundaries.")
    ]
    payload: Annotated[
        payloads.AnyPayload, Meta(description="The parallel array of values.")
    ]
    confidence: (
        Annotated[
            confidences.AnyConfidence,
            Meta(description="Optional parallel array of likelihoods or votes."),
        ]
        | UnsetType
    ) = UNSET
