# @generated by datamodel-codegen:
#   filename:  extents.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta

from .extent import (
    midi_interval,
    midi_ticks,
    pixel_box,
    quarters_interval_float,
    quarters_interval_fraction,
    quarters_time_float,
    quarters_time_fraction,
    time_frequency_box,
    time_interval,
    times,
)

type AnyExtent = Annotated[
    times.Times
    | time_interval.TimeIntervalExtent
    | time_frequency_box.TimeFrequencyBoxExtent
    | pixel_box.PixelBoxExtent
    | quarters_time_float.QuartersTimeFloat
    | quarters_time_fraction.QuartersTimeFraction
    | quarters_interval_float.QuartersIntervalFloat
    | quarters_interval_fraction.QuartersIntervalFraction
    | midi_ticks.MidiTicks
    | midi_interval.MidiInterval,
    Meta(
        description="A discriminated union of all supported columnar extent types.",
        title="Any Extent",
    ),
]
