# @generated by datamodel-codegen:
#   filename:  object.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta

from . import annotation, score_object

type AnyObject = Annotated[
    annotation.Annotation | score_object.ScoreObject,
    Meta(
        description="The root of a BOPP file: a discriminated union of all top-level object types.",
        title="Any Object",
    ),
]
