# @generated by datamodel-codegen:
#   filename:  score_object.json

from __future__ import annotations

from typing import Annotated

from msgspec import UNSET, Meta, Struct, UnsetType

from . import event_block
from . import metadata as metadata_1


class ScoreObject(Struct, tag_field="object_type", tag="score_object"):
    """
    A heterogeneous set of score events sharing one media and one timeline: each event type keeps its own strictly typed payload schema in its own block, yet all blocks travel in the same file. A tabular export is the outer union of the blocks, i.e. a sparse table where only the columns of an event's payload type are filled.
    """

    media_id: Annotated[str, Meta(pattern="^[a-zA-Z0-9]+:.*$")]
    events: Annotated[
        list[event_block.EventBlock],
        Meta(
            description="One block per event type; blocks may use different payload types but should share the extent unit."
        ),
    ]
    bopp_version: (
        Annotated[
            str,
            Meta(
                description="The Semantic Version of the BOPP schema (e.g., 1.0.0)",
                pattern="^1\\.\\d+\\.\\d+$",
            ),
        ]
        | UnsetType
    ) = UNSET
    metadata: (
        Annotated[
            metadata_1.AnnotationMetadata,
            Meta(description="The metadata describing the object"),
        ]
        | UnsetType
    ) = UNSET
