# @generated by datamodel-codegen:
#   filename:  payload/score_control_event.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta

from . import chord, dynamic, figured_bass, spanner, staff_text, system_text, tempo

type ScoreControlEventPayload = Annotated[
    chord.ScoreChordPayload
    | dynamic.ScoreDynamicPayload
    | spanner.ScoreSpannerPayload
    | figured_bass.ScoreFiguredBassPayload
    | staff_text.ScoreStaffTextPayload
    | system_text.ScoreSystemTextPayload
    | tempo.ScoreTempoPayload,
    Meta(
        description="Homogeneous columnar payloads for DLC score control events: Chord, Dynamic, Spanner, FiguredBass, StaffText, SystemText and Tempo.",
        title="Score Control Event Payload",
    ),
]
