# @generated by datamodel-codegen:
#   filename:  payload/score_control_event/chord.json

from __future__ import annotations

from typing import Annotated

from msgspec import UNSET, Meta, Struct, UnsetType

from ... import core

type StaffItem = Annotated[int, Meta(ge=1)]


type VoiceItem = Annotated[int, Meta(ge=1)]


type McItem = Annotated[int, Meta(ge=1)]


type VoltaItem = Annotated[int, Meta(ge=1)] | None


type ChordIdItem = Annotated[int, Meta(ge=0)]


class ScoreChordPayload(
    Struct, tag_field="payload_type", tag="score_control_event.chord"
):
    """
    Score control events with DLC event value 'Chord', one row per event. Columns are parallel arrays. DLC quarterbeats, quarterbeats_all_endings, duration_qb and duration are represented by the quarters_interval.fraction extent. mc_onset, mn_onset and timesig are omitted as derivable from the measures facet; event is derived from payload_type.
    """

    staff: Annotated[list[StaffItem], Meta(description="Staff numbers, 1 = top staff.")]
    voice: Annotated[
        list[VoiceItem],
        Meta(description="Voice (layer) numbers within the staff, 1-based."),
    ]
    mc: Annotated[
        list[McItem],
        Meta(
            description="Measure counts: 1-based index of the measure unit in the encoded score (ms3 'mc')."
        ),
    ]
    mn: Annotated[
        list[int],
        Meta(
            description="Measure numbers as printed in the score (ms3 'mn'; 0 for an anacrusis)."
        ),
    ]
    chord_id: Annotated[
        list[ChordIdItem],
        Meta(description="Identifier of the chord (stem), unique within the piece."),
    ]
    volta: (
        Annotated[
            list[VoltaItem],
            Meta(
                description="Volta (ending) number of the measure containing the event; null outside voltas."
            ),
        ]
        | UnsetType
    ) = UNSET
    slur: (
        Annotated[
            list[str | None],
            Meta(
                description="ms3 identifiers of slurs active at the event, e.g. '0' or '92, 93'; null when absent."
            ),
        ]
        | UnsetType
    ) = UNSET
    crescendo_hairpin: (
        Annotated[
            list[str | None],
            Meta(
                description="ms3 identifiers of crescendo hairpins active at the event, e.g. '0' or '92, 93'; null when absent."
            ),
        ]
        | UnsetType
    ) = UNSET
    decrescendo_hairpin: (
        Annotated[
            list[str | None],
            Meta(
                description="ms3 identifiers of decrescendo hairpins active at the event, e.g. '0' or '92, 93'; null when absent."
            ),
        ]
        | UnsetType
    ) = UNSET
    crescendo_line: (
        Annotated[
            list[str | None],
            Meta(
                description="ms3 identifiers of crescendo lines active at the event, e.g. '0' or '92, 93'; null when absent."
            ),
        ]
        | UnsetType
    ) = UNSET
    diminuendo_line: (
        Annotated[
            list[str | None],
            Meta(
                description="ms3 identifiers of diminuendo lines active at the event, e.g. '0' or '92, 93'; null when absent."
            ),
        ]
        | UnsetType
    ) = UNSET
    pedal: (
        Annotated[
            list[str | None],
            Meta(
                description="ms3 identifiers of pedal spanners active at the event, e.g. '0' or '92, 93'; null when absent."
            ),
        ]
        | UnsetType
    ) = UNSET
    nominal_duration: (
        Annotated[
            list[core.FractionNonnegative],
            Meta(
                description="Notated durations as fractions of a whole note before dots and tuplets are applied (e.g. [1, 4] for a quarter note)."
            ),
        ]
        | UnsetType
    ) = UNSET
    scalar: (
        Annotated[
            list[core.FractionNonnegative],
            Meta(
                description="Factors that dots and tuplets apply to nominal_duration (e.g. [3, 2] for a dotted note, [2, 3] inside a triplet)."
            ),
        ]
        | UnsetType
    ) = UNSET
    gracenote: (
        Annotated[
            list[str | None],
            Meta(
                description="Grace note type of the chord (e.g. 'acciaccatura', 'appoggiatura', 'grace16'); null for regular chords."
            ),
        ]
        | UnsetType
    ) = UNSET
    articulation: (
        Annotated[
            list[str | None],
            Meta(
                description="Articulation markings attached to the chord as encoded by ms3; null when absent."
            ),
        ]
        | UnsetType
    ) = UNSET
    tremolo: (
        Annotated[
            list[str | None],
            Meta(
                description="Tremolo specification as encoded by the source (e.g. '1/2_r16_0'); null when absent."
            ),
        ]
        | UnsetType
    ) = UNSET
    lyrics_1: (
        Annotated[
            list[str | None],
            Meta(
                description="Lyric text attached to the chord in verse 1; null when absent."
            ),
        ]
        | UnsetType
    ) = UNSET
    lyrics_2: (
        Annotated[
            list[str | None],
            Meta(
                description="Lyric text attached to the chord in verse 2; null when absent."
            ),
        ]
        | UnsetType
    ) = UNSET
    lyrics_3: (
        Annotated[
            list[str | None],
            Meta(
                description="Lyric text attached to the chord in verse 3; null when absent."
            ),
        ]
        | UnsetType
    ) = UNSET
