# @generated by datamodel-codegen:
#   filename:  payload/score_control_event/figured_bass.json

from __future__ import annotations

from typing import Annotated

from msgspec import UNSET, Meta, Struct, UnsetType

from ... import core

type StaffItem = Annotated[int, Meta(ge=1)]


type VoiceItem = Annotated[int, Meta(ge=1)]


type McItem = Annotated[int, Meta(ge=1)]


type VoltaItem = Annotated[int, Meta(ge=1)] | None


class ScoreFiguredBassPayload(
    Struct, tag_field="payload_type", tag="score_control_event.figured_bass"
):
    """
    Score control events with DLC event value 'FiguredBass', one row per event. Columns are parallel arrays. DLC quarterbeats, quarterbeats_all_endings, duration_qb and duration are represented by the quarters_interval.fraction extent. mc_onset, mn_onset and timesig are omitted as derivable from the measures facet; event is derived from payload_type.
    """

    staff: Annotated[list[StaffItem], Meta(description="Staff numbers, 1 = top staff.")]
    voice: Annotated[
        list[VoiceItem],
        Meta(description="Voice (layer) numbers within the staff, 1-based."),
    ]
    mc: Annotated[
        list[McItem],
        Meta(
            description="Measure counts: 1-based index of the measure unit in the encoded score (ms3 'mc')."
        ),
    ]
    mn: Annotated[
        list[int],
        Meta(
            description="Measure numbers as printed in the score (ms3 'mn'; 0 for an anacrusis)."
        ),
    ]
    thoroughbass_duration: Annotated[
        list[core.FractionNonnegative],
        Meta(
            description="Duration of the figured bass indication as a fraction of a whole note."
        ),
    ]
    volta: (
        Annotated[
            list[VoltaItem],
            Meta(
                description="Volta (ending) number of the measure containing the event; null outside voltas."
            ),
        ]
        | UnsetType
    ) = UNSET
    slur: (
        Annotated[
            list[str | None],
            Meta(
                description="ms3 identifiers of slurs active at the event, e.g. '0' or '92, 93'; null when absent."
            ),
        ]
        | UnsetType
    ) = UNSET
    crescendo_hairpin: (
        Annotated[
            list[str | None],
            Meta(
                description="ms3 identifiers of crescendo hairpins active at the event, e.g. '0' or '92, 93'; null when absent."
            ),
        ]
        | UnsetType
    ) = UNSET
    decrescendo_hairpin: (
        Annotated[
            list[str | None],
            Meta(
                description="ms3 identifiers of decrescendo hairpins active at the event, e.g. '0' or '92, 93'; null when absent."
            ),
        ]
        | UnsetType
    ) = UNSET
    crescendo_line: (
        Annotated[
            list[str | None],
            Meta(
                description="ms3 identifiers of crescendo lines active at the event, e.g. '0' or '92, 93'; null when absent."
            ),
        ]
        | UnsetType
    ) = UNSET
    diminuendo_line: (
        Annotated[
            list[str | None],
            Meta(
                description="ms3 identifiers of diminuendo lines active at the event, e.g. '0' or '92, 93'; null when absent."
            ),
        ]
        | UnsetType
    ) = UNSET
    pedal: (
        Annotated[
            list[str | None],
            Meta(
                description="ms3 identifiers of pedal spanners active at the event, e.g. '0' or '92, 93'; null when absent."
            ),
        ]
        | UnsetType
    ) = UNSET
    thoroughbass_level_1: (
        Annotated[
            list[str | None],
            Meta(
                description="Figured bass symbol on level 1 of the indication; null when absent."
            ),
        ]
        | UnsetType
    ) = UNSET
    thoroughbass_level_2: (
        Annotated[
            list[str | None],
            Meta(
                description="Figured bass symbol on level 2 of the indication; null when absent."
            ),
        ]
        | UnsetType
    ) = UNSET
    thoroughbass_level_3: (
        Annotated[
            list[str | None],
            Meta(
                description="Figured bass symbol on level 3 of the indication; null when absent."
            ),
        ]
        | UnsetType
    ) = UNSET
    thoroughbass_level_4: (
        Annotated[
            list[str | None],
            Meta(
                description="Figured bass symbol on level 4 of the indication; null when absent."
            ),
        ]
        | UnsetType
    ) = UNSET
