# @generated by datamodel-codegen:
#   filename:  payload/score_control_event/tempo.json

from __future__ import annotations

from typing import Annotated

from msgspec import UNSET, Meta, Struct, UnsetType

type StaffItem = Annotated[int, Meta(ge=1)]


type VoiceItem = Annotated[int, Meta(ge=1)]


type McItem = Annotated[int, Meta(ge=1)]


type VoltaItem = Annotated[int, Meta(ge=1)] | None


type QpmItem = Annotated[float, Meta(gt=0.0)]


type MetronomeNumberItem = Annotated[float, Meta(gt=0.0)] | None


class ScoreTempoPayload(
    Struct, tag_field="payload_type", tag="score_control_event.tempo"
):
    """
    Score control events with DLC event value 'Tempo', one row per event. Columns are parallel arrays. DLC quarterbeats, quarterbeats_all_endings, duration_qb and duration are represented by the quarters_interval.fraction extent. mc_onset, mn_onset and timesig are omitted as derivable from the measures facet; event is derived from payload_type.
    """

    staff: Annotated[list[StaffItem], Meta(description="Staff numbers, 1 = top staff.")]
    voice: Annotated[
        list[VoiceItem],
        Meta(description="Voice (layer) numbers within the staff, 1-based."),
    ]
    mc: Annotated[
        list[McItem],
        Meta(
            description="Measure counts: 1-based index of the measure unit in the encoded score (ms3 'mc')."
        ),
    ]
    mn: Annotated[
        list[int],
        Meta(
            description="Measure numbers as printed in the score (ms3 'mn'; 0 for an anacrusis)."
        ),
    ]
    qpm: Annotated[
        list[QpmItem], Meta(description="Tempo in quarter notes per minute.")
    ]
    tempo_visible: Annotated[
        list[bool],
        Meta(description="Whether the tempo marking is visible in the score."),
    ]
    volta: (
        Annotated[
            list[VoltaItem],
            Meta(
                description="Volta (ending) number of the measure containing the event; null outside voltas."
            ),
        ]
        | UnsetType
    ) = UNSET
    slur: (
        Annotated[
            list[str | None],
            Meta(
                description="ms3 identifiers of slurs active at the event, e.g. '0' or '92, 93'; null when absent."
            ),
        ]
        | UnsetType
    ) = UNSET
    crescendo_hairpin: (
        Annotated[
            list[str | None],
            Meta(
                description="ms3 identifiers of crescendo hairpins active at the event, e.g. '0' or '92, 93'; null when absent."
            ),
        ]
        | UnsetType
    ) = UNSET
    decrescendo_hairpin: (
        Annotated[
            list[str | None],
            Meta(
                description="ms3 identifiers of decrescendo hairpins active at the event, e.g. '0' or '92, 93'; null when absent."
            ),
        ]
        | UnsetType
    ) = UNSET
    crescendo_line: (
        Annotated[
            list[str | None],
            Meta(
                description="ms3 identifiers of crescendo lines active at the event, e.g. '0' or '92, 93'; null when absent."
            ),
        ]
        | UnsetType
    ) = UNSET
    diminuendo_line: (
        Annotated[
            list[str | None],
            Meta(
                description="ms3 identifiers of diminuendo lines active at the event, e.g. '0' or '92, 93'; null when absent."
            ),
        ]
        | UnsetType
    ) = UNSET
    pedal: (
        Annotated[
            list[str | None],
            Meta(
                description="ms3 identifiers of pedal spanners active at the event, e.g. '0' or '92, 93'; null when absent."
            ),
        ]
        | UnsetType
    ) = UNSET
    tempo: (
        Annotated[
            list[str | None],
            Meta(description="Text of the tempo marking; null when absent."),
        ]
        | UnsetType
    ) = UNSET
    metronome_base: (
        Annotated[
            list[str | None],
            Meta(
                description="Notated beat unit of the metronome marking; null when absent."
            ),
        ]
        | UnsetType
    ) = UNSET
    metronome_number: (
        Annotated[
            list[MetronomeNumberItem],
            Meta(
                description="Number of metronome beat units per minute; null when absent."
            ),
        ]
        | UnsetType
    ) = UNSET
